# Generated by Django 5.2.5 on 2025-12-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSensor',
            fields=[
                ('id_estado_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SensorRFID',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('alias', models.CharField(max_length=100)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
                ('id_estado_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.estadosensor')),
            ],
        ),
    ]
