# Generated by Django 5.2.5 on 2025-12-12 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barreras', '0001_initial'),
        ('departamentos', '0001_initial'),
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAcceso',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid_leido', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=50)),
                ('detalle', models.TextField()),
                ('id_barrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barreras.barrera')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.sensorrfid')),
            ],
        ),
    ]
