# Generated by Django 5.2.5 on 2025-12-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBarrera',
            fields=[
                ('id_estado_barrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Barrera',
            fields=[
                ('id_barrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('id_estado_barrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barreras.estadobarrera')),
            ],
        ),
    ]
